import {
  Sparkles,
  PenTool,
  GitMerge,
  Moon,
  Languages,
  Lock,
  FileText,
  Scissors,
  Minimize2,
  Type,
  type LucideIcon,
} from "lucide-react";

export type ToolType =
  | "summarize"
  | "annotate"
  | "merge"
  | "dark-mode"
  | "translate"
  | "protect"
  | "convert"
  | "delete-pages"
  | "compress"
  | "watermark"
  | "page-numbers"
  | "convert-pdf";

export interface ToolModalConfig {
  title: string;
  description: string;
  icon: LucideIcon;
  iconBg: string;
  iconColor: string;
  buttonText: string;
  dropHint: string;
  accept: string;
  multiple: boolean;
  maxFiles: number;
  maxSizeMb: number;
  accentButton: string;
  accentButtonHover: string;
  dropzoneBorder: string;
  dropzoneBg: string;
  formatsLabel: string;
  cardBg: string;
  cardBorder: string;
  tagBg: string;
  tagColor: string;
}

export const TOOL_MODAL_CONFIG: Record<ToolType, ToolModalConfig> = {
  summarize: {
    title: "Summarize PDF",
    description: "Get instant AI-generated summaries of your PDFs in seconds.",
    icon: Sparkles,
    iconBg: "bg-white",
    iconColor: "text-[#FF4D6D]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#FF4D6D]",
    accentButtonHover: "hover:bg-[#E63958]",
    dropzoneBorder: "border-[#FFE2E6]",
    dropzoneBg: "bg-[#FFF0F2]",
    formatsLabel: "PDF",
    cardBg: "bg-[#FFD6DE]",
    cardBorder: "border-[#FFC0CC]",
    tagBg: "bg-[#FFCCD5]",
    tagColor: "text-[#FF4D6D]",
  },
  annotate: {
    title: "Annotate PDF",
    description: "Edit existing text, add notes, and sign your PDF with ease.",
    icon: PenTool,
    iconBg: "bg-white",
    iconColor: "text-[#007AFF]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#007AFF]",
    accentButtonHover: "hover:bg-[#0062CC]",
    dropzoneBorder: "border-[#E0EEFF]",
    dropzoneBg: "bg-[#F0F7FF]",
    formatsLabel: "PDF",
    cardBg: "bg-[#D6E8FF]",
    cardBorder: "border-[#BDD5FF]",
    tagBg: "bg-[#C8DFFF]",
    tagColor: "text-[#007AFF]",
  },
  merge: {
    title: "Merge PDF",
    description: "Combine multiple PDF files into a single document.",
    icon: GitMerge,
    iconBg: "bg-white",
    iconColor: "text-[#22C55E]",
    buttonText: "Select Multiple PDFs",
    dropHint: "or drag & drop PDFs here",
    accept: "application/pdf,.pdf",
    multiple: true,
    maxFiles: 10,
    maxSizeMb: 25,
    accentButton: "bg-[#22C55E]",
    accentButtonHover: "hover:bg-[#1BA14D]",
    dropzoneBorder: "border-[#E0FFE8]",
    dropzoneBg: "bg-[#F0FFF4]",
    formatsLabel: "PDF",
    cardBg: "bg-[#C8F0D6]",
    cardBorder: "border-[#AEEAC0]",
    tagBg: "bg-[#BAEECE]",
    tagColor: "text-[#22C55E]",
  },
  watermark: {
    title: "Add Watermark",
    description: "Add a custom text watermark to every page of your PDF.",
    icon: Type,
    iconBg: "bg-white",
    iconColor: "text-[#22C55E]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#22C55E]",
    accentButtonHover: "hover:bg-[#1BA14D]",
    dropzoneBorder: "border-[#E0FFE8]",
    dropzoneBg: "bg-[#F0FFF4]",
    formatsLabel: "PDF",
    cardBg: "bg-[#C8F0D6]",
    cardBorder: "border-[#AEEAC0]",
    tagBg: "bg-[#BAEECE]",
    tagColor: "text-[#22C55E]",
  },
  "dark-mode": {
    title: "Dark Mode",
    description: "Download a dark-theme PDF without inverting images.",
    icon: Moon,
    iconBg: "bg-white",
    iconColor: "text-[#F59E0B]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#F59E0B]",
    accentButtonHover: "hover:bg-[#D97E06]",
    dropzoneBorder: "border-[#FFEFD6]",
    dropzoneBg: "bg-[#FFF9F0]",
    formatsLabel: "PDF",
    cardBg: "bg-[#FFEABC]",
    cardBorder: "border-[#FFD98A]",
    tagBg: "bg-[#FFE2A8]",
    tagColor: "text-[#F59E0B]",
  },
  translate: {
    title: "Translate PDF",
    description: "Translate your PDF to any language with one click.",
    icon: Languages,
    iconBg: "bg-white",
    iconColor: "text-[#8B5CF6]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#8B5CF6]",
    accentButtonHover: "hover:bg-[#7C3AED]",
    dropzoneBorder: "border-[#EEE0FF]",
    dropzoneBg: "bg-[#F7F0FF]",
    formatsLabel: "PDF",
    cardBg: "bg-[#E8D6FF]",
    cardBorder: "border-[#D9BFFF]",
    tagBg: "bg-[#DFCCFF]",
    tagColor: "text-[#8B5CF6]",
  },
  protect: {
    title: "Protect PDF",
    description: "Password protect your PDF and keep it secure.",
    icon: Lock,
    iconBg: "bg-white",
    iconColor: "text-[#F43F5E]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#F43F5E]",
    accentButtonHover: "hover:bg-[#E11D48]",
    dropzoneBorder: "border-[#FFE0E0]",
    dropzoneBg: "bg-[#FFF0F0]",
    formatsLabel: "PDF",
    cardBg: "bg-[#FFD6D6]",
    cardBorder: "border-[#FFBCBC]",
    tagBg: "bg-[#FFCACA]",
    tagColor: "text-[#F43F5E]",
  },
  "delete-pages": {
    title: "Delete Pages",
    description: "Remove specific pages from your PDF instantly.",
    icon: Scissors,
    iconBg: "bg-white",
    iconColor: "text-[#F97316]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#F97316]",
    accentButtonHover: "hover:bg-[#EA6C00]",
    dropzoneBorder: "border-[#FFEFD6]",
    dropzoneBg: "bg-[#FFF9F0]",
    formatsLabel: "PDF",
    cardBg: "bg-[#FFE5C8]",
    cardBorder: "border-[#FFD4A8]",
    tagBg: "bg-[#FFDAB8]",
    tagColor: "text-[#F97316]",
  },
  "page-numbers": {
    title: "Add Page Numbers",
    description: "Add bottom-center page numbers to every page of your PDF.",
    icon: FileText,
    iconBg: "bg-white",
    iconColor: "text-[#4F46E5]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#4F46E5]",
    accentButtonHover: "hover:bg-[#4338CA]",
    dropzoneBorder: "border-[#EEF2FF]",
    dropzoneBg: "bg-[#F5F7FF]",
    formatsLabel: "PDF",
    cardBg: "bg-[#EEF2FF]",
    cardBorder: "border-[#E0E7FF]",
    tagBg: "bg-[#E0E7FF]",
    tagColor: "text-[#4F46E5]",
  },
  "convert-pdf": {
    title: "Convert PDF",
    description: "Convert your PDF to Word, Excel, PPT, JPG and more.",
    icon: FileText,
    iconBg: "bg-white",
    iconColor: "text-[#0D9488]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#0D9488]",
    accentButtonHover: "hover:bg-[#0F766E]",
    dropzoneBorder: "border-[#F0FDFA]",
    dropzoneBg: "bg-[#F5FFFE]",
    formatsLabel: "PDF",
    cardBg: "bg-[#F0FDFA]",
    cardBorder: "border-[#CCFBF1]",
    tagBg: "bg-[#CCFBF1]",
    tagColor: "text-[#0D9488]",
  },
  compress: {
    title: "Compress PDF",
    description: "Reduce PDF file size without losing quality.",
    icon: Minimize2,
    iconBg: "bg-white",
    iconColor: "text-[#F97316]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#F97316]",
    accentButtonHover: "hover:bg-[#EA6C00]",
    dropzoneBorder: "border-[#FFECD6]",
    dropzoneBg: "bg-[#FFF6F0]",
    formatsLabel: "PDF",
    cardBg: "bg-[#FFE2C8]",
    cardBorder: "border-[#FFD0A8]",
    tagBg: "bg-[#FFD8B8]",
    tagColor: "text-[#F97316]",
  },
  convert: {
    title: "Convert to Markdown",
    description: "Extract text-based PDFs into clean, downloadable Markdown.",
    icon: FileText,
    iconBg: "bg-white",
    iconColor: "text-[#0EA5E9]",
    buttonText: "Select PDF File",
    dropHint: "or drag & drop PDF here",
    accept: "application/pdf,.pdf",
    multiple: false,
    maxFiles: 1,
    maxSizeMb: 20,
    accentButton: "bg-[#0EA5E9]",
    accentButtonHover: "hover:bg-[#0369A1]",
    dropzoneBorder: "border-[#E0F4FF]",
    dropzoneBg: "bg-[#F0FAFF]",
    formatsLabel: "PDF",
    cardBg: "bg-[#C8EEFF]",
    cardBorder: "border-[#A8E0FF]",
    tagBg: "bg-[#BAE8FF]",
    tagColor: "text-[#0EA5E9]",
  },
};

export const MODAL_TOOL_IDS: ToolType[] = [
  "summarize",
  "annotate",
  "merge",
  "dark-mode",
  "translate",
  "protect",
  "convert",
  "delete-pages",
  "compress",
  "watermark",
  "page-numbers",
  "convert-pdf",
];

export function isModalTool(id: string): id is ToolType {
  return MODAL_TOOL_IDS.includes(id as ToolType);
}
